FROM node:17-alpine

ARG GIT_TAG
ARG GIT_BRANCH
ARG GIT_REVISION

WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY patches ./patches

RUN yarn install

COPY public ./public
COPY src ./src
COPY .env .

ENV NODE_ENV production
ENV NODE_OPTIONS --max_old_space_size=4096

ENV REACT_APP_GIT_TAG=${GIT_TAG}
ENV REACT_APP_GIT_BRANCH=${GIT_BRANCH}
ENV REACT_APP_GIT_REVISION=${GIT_REVISION}

RUN yarn build
# This command export the website under ./build folder as single page application
RUN yarn staticize-spa

# This command export the website under ./build-static as static web site
RUN yarn staticize
